name: Build x86 Image

on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'docs/**'
    - 'dist/**'
    - 'yamls/**'
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - 'yamls/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.4.0

      - name: Unit test
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          make ut

      - name: Build
        run: make release

      - name: Init Kind
        run: |
          sudo make kind-init

      - name: Run E2E
        run: |
          sudo kubectl cluster-info
          sudo chmod 666 /home/runner/.kube/config
          make e2e

      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ALAUDA_USERNAME: ${{ secrets.ALAUDA_USERNAME }}
          ALAUDA_PASSWORD: ${{ secrets.ALAUDA_PASSWORD }}
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker images
          docker push kubeovn/kube-ovn:$TAG
