name: Build arm64 Image
on:
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - 'yamls/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.4.0
      - name: Build
        run: make release-arm
      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          TAG=$(cat VERSION)
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker images
          docker tag kubeovn/kube-ovn:$TAG kubeovn/kube-ovn:$TAG-arm
          docker push kubeovn/kube-ovn:$TAG-arm
